//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Customers_Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChienDichQuangCao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChienDichQuangCao()
        {
            this.ChiTietChienDichQuangCao = new HashSet<ChiTietChienDichQuangCao>();
        }
    
        public string IdChienDich { get; set; }
        public string TenChienDich { get; set; }
        public string IdQuangCao { get; set; }
    
        public virtual QuangCao QuangCao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChienDichQuangCao> ChiTietChienDichQuangCao { get; set; }
    }
}
