//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Customers_Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonNhapHang
    {
        public string IdNhapHang { get; set; }
        public string IdSanPham { get; set; }
        public string IdNhaCungCap { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> GiaNhap { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhapHang NhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
