//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Customers_Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChienDichQuangCao
    {
        public string IdChiTietChienDich { get; set; }
        public string IdChienDich { get; set; }
        public string KenhQuangCao { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<int> SoLuotClick { get; set; }
    
        public virtual ChienDichQuangCao ChienDichQuangCao { get; set; }
    }
}
