//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Customers_Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        public string IdKhoHang { get; set; }
        public string IdChiNhanh { get; set; }
        public string TenKhoHang { get; set; }
        public string IdSanPham { get; set; }
        public string DiaChiKhoHang { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
