//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Customers_Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class YkienKH
    {
        public string IdFeedback { get; set; }
        public string IdKhachHang { get; set; }
        public Nullable<System.DateTime> NgayYkien { get; set; }
        public string NDYkien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
